Repository Todoary/Todoary-iOS, pull requests merged in 2022-09, with the labels that each got.

#301 #294 투두 접근 프로세스 변경 및 #297 이슈 close
  Todoary-iOS/Todoary/API/User/UserDeleteDataManager/UserDeleteDataManager.swift
  Todoary-iOS/Todoary/Auth/Login/LoginViewController.swift
  Todoary-iOS/Todoary/CommonSource/Alert/BaseAlertViewController.swift
  Todoary-iOS/Todoary/CommonSource/Alert/CancelAlertViewController.swift
  Todoary-iOS/Todoary/Home/Summary/Cell/TodoListTableViewCell.swift
  Todoary-iOS/Todoary/Home/Summary/SummaryBottomViewController.swift
  Todoary-iOS/Todoary/User/Account/AccountViewController.swift
Labels: 💭SSOOYA, ⭐️ feat

#305 남은VC에 커스텀 팝업 적용
  Todoary-iOS/Todoary.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Todoary-iOS/Todoary/API/Auth/AuthJwtDataManager.swift
  Todoary-iOS/Todoary/API/Auth/AutoLoginDataManager/AutoLoginDataManager.swift
  Todoary-iOS/Todoary/API/Auth/LoginDataManager/LoginDataManager.swift
  Todoary-iOS/Todoary/AppDelegate.swift
  Todoary-iOS/Todoary/Auth/PwFind/PwFindViewController.swift
  Todoary-iOS/Todoary/Diary/DiaryViewController.swift
  Todoary-iOS/Todoary/Home/ColorPicker/ColorPickerViewController.swift
  Todoary-iOS/Todoary/Home/HomeViewController.swift
  Todoary-iOS/Todoary/Home/TodoSetting/TodoSettingViewController.swift
  Todoary-iOS/Todoary/User/Account/AccountViewController.swift
  Todoary-iOS/Todoary/User/Profile/ProfileViewController.swift
Labels: 🌸HOLA, 🔧fix

#308 #300, #304, #307, #310 issue close
  Todoary-iOS/Pods/Pods.xcodeproj/project.pbxproj
  Todoary-iOS/Todoary.xcodeproj/project.pbxproj
  Todoary-iOS/Todoary.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Todoary-iOS/Todoary/Assets.xcassets/Home/push_pin_big_fill.imageset/Contents.json
  Todoary-iOS/Todoary/Assets.xcassets/Home/push_pin_big_fill.imageset/push_pin.svg
  Todoary-iOS/Todoary/Auth/Login/LoginViewController.swift
  Todoary-iOS/Todoary/CommonSource/Alert/BaseAlertViewController.swift
  Todoary-iOS/Todoary/CommonSource/Const.swift
  Todoary-iOS/Todoary/Home/Summary/Cell/HiddenTransparentButtonView.swift
  Todoary-iOS/Todoary/Home/Summary/Cell/TodoListTableViewCell.swift
  Todoary-iOS/Todoary/Home/Summary/SummaryBottomSheetViewController+Layout.swift
  Todoary-iOS/Todoary/Home/Summary/SummaryBottomViewController.swift
  Todoary-iOS/Todoary/Home/TodoSetting/TodoSettingViewController.swift
Labels: 🔥 bug, 💭SSOOYA

#312 #311: 알람 alert 파일 추가 및 UI 구현 & 요약VC 알람 아이콘 asset 추가
  Todoary-iOS/Todoary.xcodeproj/project.pbxproj
  Todoary-iOS/Todoary/Assets.xcassets/Home/alarm.imageset/Contents.json
  Todoary-iOS/Todoary/Assets.xcassets/Home/alarm_activate.imageset/Contents.json
  Todoary-iOS/Todoary/Assets.xcassets/Home/alarm_activate.imageset/alarm.svg
  Todoary-iOS/Todoary/CommonSource/Alert/AlarmAlertViewController.swift
  Todoary-iOS/Todoary/Home/Summary/SummaryBottomViewController.swift
Labels: 💭SSOOYA, ⭐️ feat

#314 #311: 투두 알림 시간 스피너 설정 및 API 파일 추가
  Todoary-iOS/Todoary.xcodeproj/project.pbxproj
  Todoary-iOS/Todoary/CommonSource/Alert/AlarmAlertViewController.swift
  Todoary-iOS/Todoary/Home/Summary/Cell/HiddenTransparentButtonView.swift
  Todoary-iOS/Todoary/Home/Summary/Cell/TodoListTableViewCell.swift
  Todoary-iOS/Todoary/Home/Summary/SummaryBottomViewController.swift
  Todoary-iOS/Todoary/Home/Summary/TodoAlarmDataManager/TodoAlarmDataManager.swift
  Todoary-iOS/Todoary/Home/Summary/TodoAlarmDataManager/TodoAlarmInput.swift
  Todoary-iOS/Todoary/Home/TodoSetting/TodoSettingDataManager/TodoSettingInput.swift
Labels: 💭SSOOYA, ⭐️ feat

#318 #317 issue close
  Todoary-iOS/Todoary.xcodeproj/project.pbxproj
  Todoary-iOS/Todoary/Home/Summary/AddButtonViewController.swift
  Todoary-iOS/Todoary/Home/Summary/Cell/TodoListTableViewCell.swift
  Todoary-iOS/Todoary/Home/Summary/Cell/TodoListTitleCell.swift
  Todoary-iOS/Todoary/Home/Summary/SummaryBottomSheetViewController+Layout.swift
  Todoary-iOS/Todoary/Home/Summary/SummaryBottomViewController.swift
Labels: 💭SSOOYA, ⭐️ feat
